name: spanischer-verein
services:
  web:
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
      target: production
    ports:
      - ${PORT}:${PORT}
    labels:
      # Redirect to non-www
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www\.(.*)
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$${1}
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true
    environment:
      - SANITY_PERSPECTIVE=${SANITY_PERSPECTIVE}
      - SANITY_DATASET=${SANITY_DATASET}
      - SANITY_TOKEN=${SANITY_TOKEN}
      - ORIGIN=${WEB__ORIGIN}
      - PUBLIC_ORIGIN=${WEB__ORIGIN}

  newsletter-service:
    build:
      context: .
      dockerfile: .docker/newsletter/Dockerfile
      target: production
    environment:
      - MAILCHIMP_API_KEY=${NEWSLETTER__MAILCHIMP_API_KEY:?}
      - MAILCHIMP_LIST_ID=${NEWSLETTER__MAILCHIMP_LIST_ID:?}
      - SANITY_PROJECT_ID=${NEWSLETTER__SANITY_PROJECT_ID:?}
      - SANITY_API_TOKEN=${NEWSLETTER__SANITY_API_TOKEN:?}
      - SANITY_DATASET=${NEWSLETTER__SANITY_DATASET:?}
      - BASE_URL=${NEWSLETTER__BASE_URL:?}
