name: spanischer-verein
services:
  web:
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
      target: production
    ports:
      - ${PORT}:${PORT}
    labels:
      # Redirect to non-www
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www\.(.*)
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$${1}
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true
    environment:
      - SANITY_PERSPECTIVE=${SANITY_PERSPECTIVE}
      - SANITY_DATASET=${SANITY_DATASET}
      - SANITY_TOKEN=${SANITY_TOKEN}
      - MAIL_CREDENTIALS=${MAIL_CREDENTIALS}
      - MAIL_SERVER=${MAIL_SERVER}
